services:
  node:
    container_name: node
    build: .
    ports:
      -  "3000:3000"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: "${DB_HOST}"
    image: "mysql:oracle"
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=$(PASSWORD)
      - MYSQL_ROOT_PASSWORD=$(ROOT_PASSWORD)
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db: